### ISSUE TITLE
Error on startup on SD.Next. object has no attribute 'needs_reload_ui'

### ISSUE THREAD

**Issue by FutonGama** [nihedon/sd-webui-weight-helper#3]
19:27:53-370166 ERROR    executing callback:
                         C:\Programas\StableDiffusion\automatic\extensions\sd-webui-weight-helper\scripts\weight_helper.py
                         ui_settings_callback: AttributeError
┌───────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────┐
│ C:\Programas\StableDiffusion\automatic\modules\script_callbacks.py:205 in ui_settings_callback                                      │
│                                                                                                                                     │
│   204 │   │   │   t0 = time.time()                                                                                                  │
│ > 205 │   │   │   c.callback()                                                                                                      │
│   206 │   │   │   timer(t0, c.script, 'ui_settings')                                                                                │
│                                                                                                                                     │
│ C:\Programas\StableDiffusion\automatic\extensions\sd-webui-weight-helper\scripts\weight_helper.py:11 in on_ui_settings              │
│                                                                                                                                     │
│   10 │   shared.options_templates.update(shared.options_section(section, {                                                          │
│ > 11 │   │   'weight_helper_enabled': shared.OptionInfo(True, 'Enabled').needs_reload_ui(),                                         │
│   12 │   │   'weight_helper_context_menu_scale': shared.OptionInfo(0.9, "Context menu scale",                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ AttributeError: 'OptionInfo' object has no attribute 'needs_reload_ui'

I have tried re-install and other kind of stuff, nothing worked. So the UI is not showing-up when click on Lora. Also i'm using Firefox and its working on original A1111 for me.

**Comment by nihedon** [comment]
@FutonGama 

Thank you for your contact.
“needs_reload_ui” is a function for A1111, and it seems that it is not available in SD.Next. I thought it was kind, because it shows “(requires Reload UI)” on the setting screen, but it seems to have compatibility issues, so I will delete it. Please update to the latest version.
I have not tested it on SD.Next, so I would appreciate it if you could let me know if you find any problems.

**Comment by nihedon** [comment]
Since there has been no further update, I'll consider the issue resolved.

**Comment by RGX650** [comment]
just as info:  in SDNEXT "needs_reload_ui" can be replaced by  "needs_restart"

Another kind of way around:
https://github.com/John-WL/sd-webui-backend-console/commit/f0835c606844840b302e553ca5d27ae5c7ebe4b9

**Comment by RGX650** [comment]
just sharing findings ^^
