### ISSUE TITLE
LyCORIS(SDXL) にて OUT08 が対象外で19桁となっていますが、OUT08 を含めた 20桁がLoRA Block Weight側の仕様ではありませんでしょうか？

### ISSUE THREAD

**Issue by Zuntan03** [nihedon/sd-webui-weight-helper#4]
LyCORIS(SDXL) にて OUT08 が対象外で19桁となっていますが、OUT08 を含めた 20桁がLoRA Block Weight側の仕様ではありませんでしょうか？

https://github.com/nihedon/sd-webui-weight-helper/blob/ff7ca4142b91180941cfde0aaa5c36ecb5db508b/javascript/weight_helper.js#L62

https://github.com/hako-mikan/sd-webui-lora-block-weight/blob/1fa7eb78f59af791183d6ed35972039c34b51fad/scripts/lora_block_weight.py#L55

**Comment by nihedon** [comment]
@Zuntan03 
報告ありがとうございます！

READMEに書いてある表がちょっとおかしかったので自信なかったのですが、
OUT08を含めるのが正しいようですね。

先ほどOUT08を含めて20桁に変更したバージョンをコミットしました。
最新版にして試してみてください。

**Comment by Zuntan03** [comment]
対応ありがとうございます。
修正を確認いたしました。
