### ISSUE TITLE
LoRA-C3Lierの対応

### ISSUE THREAD

**Issue by waomodder** [nihedon/sd-webui-weight-helper#5]
この度、プラグインを作っていただいてありがとうございます。
早速ですが、タイトル通りLoRAの種類のC3Lierという形式に対応していただきたいです。

C3LierはKohya氏がLycorisのLoconをアレンジしたLoraの形式の一種で基本はLoconと階層構造は同じものとなっています。
このプラグインのLycoris設定で値を調整するとプロンプトのLora指定がlyco:になってしまいますが、lora:にしないと動作しないのでわざわざ手直しをしないといけない手間が発生します。

そこで、C3Lierの設定を追加してLora指定の部分をlora:に置き換えていただくだけで手直しの手間が省けるので助かります。
是非ともC3Lier形式の設定を追加していただけるよう検討してほしいです。
よろしくお願いいたします。

**Comment by waomodder** [comment]
label:enhancement

**Comment by nihedon** [comment]
@waomodder 
使っていただいてありがとうございます！
また、C3Lierについて詳細ありがとうございます。

コメントいただいた内容を確認しました。
即修正をしようと思ったのですが、その前に2点ほど確認させてください。

1. 使用しているWeb-UI
A1111, SD-NEXT, Forgeなどいろいろありますが、その中でどれを使用されてますか？
2. 「lora:にしないと動作しない」について
これは「ブロックウェイトが有効にならない（全て1扱い）」という認識であってますか？

当方A1111を使用しています。
C3Lierで作成されたLoRAをダウンロードし、以下２パターンを試してみました。
`<lora:{lora_name}:5:lbw=0,1,0,0,1,0,0,1,0,0,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0>`
`<lyco:{lora_name}:5:lbw=0,1,0,0,1,0,0,1,0,0,1,1,1,0,1,1,1,0,0,0,0,0,0,0,0,0>`
※TEncを5に変更し、「lyco - lora」のウェイトを有効にした定義です。
　これによりLoRA範囲外のブロックの変化が確認できます。
　純粋なLoRAであればTEncが5であっても一切変更が起きない設定値です。

その結果、どちらも同じ変化が起きたためタグ名はloraでもlycoでも変わらないことがわかりました。

このことからhako-mikan氏のlora-block-weightの実装も確認したのですが、
やはりA1111の場合はタグ名による処理分岐はない作りとなっているようです。
（軽く見ただけなので断定はできないですが。。。）

ただし、ForgeやSD-NEXTを使用した場合はプリインストールされている拡張機能が違うため
タグ名を正しく指定しなくてはならない可能性があります。

この質問の背景として、その他のLoHaやLoKRなども対応が必要か？という疑問が湧いたためです。
回答よろしくおねがいします :bowing_man:

**Comment by waomodder** [comment]
ご検討してい頂き、誠にありがとうございます。

1.使用しているWeb-UI
仕様している環境はA1111 WEBUI Ver1.7.0です。

2.「lora:にしないと動作しない」について
当環境ではC3Lier呼び出し文法がlora:にしないとブロックウエイトが有効にならないのと同時に、WEBUIがC3LierをLoraとして認識してくれません。
C3Lierの中身はほぼLoconなんですが、学習モジュールがKohya版Lora(LierLa)と同様に「networks.lora」を使用しているためだと思われます。
拡張に関しても追加でなにも入れずにC3LierはLoraとして使用できました。

**Comment by nihedon** [comment]
@waomodder 
回答ありがとうございます。

確認したのですが、やはりこちらではloraでもlycoでも正しくウェイトが反映されました。。。
もしかしたら何かの拡張機能により正しく制御されているかもしれないので、なんとも言えない状況です。

※回答いただいた内容を元にそれに該当するモデルを検索しました。
　おそらく以下のモデルがnetworks.loraを使用したC3Lierかと思います。
　アクセスする場合、SFWですが念の為ご注意ください。
　ttps://civitai.com/models/7033?modelVersionId=246250

他の実装モジュールでも「loraタグ且つ26ブロック指定が可能」なものもありそうなので、
以下のようなUIに変更予定です。（変更する可能性あります）
<img src="https://github.com/nihedon/sd-webui-weight-helper/assets/66118290/ffb8aef4-e46b-4164-9b0c-5eea116e3f9a)" height="400"></img>

ご不便おかけして申し訳ないですが
現在対応中ですので完了までしばらくお待ち下さい！

<参考>
https://wikiwiki.jp/sd_toshiaki/LoRA%E3%81%AE%E7%A8%AE%E9%A1%9E

**Comment by nihedon** [comment]
@waomodder 
本件対応しました。
最新版に更新し確認おねがいします！

また何か質問や改善案等ありましたらよろしくおねがいします。

**Comment by waomodder** [comment]
動作確認できました！
素早い対応ありがとうございました！

**Comment by nihedon** [comment]
本件は解決済みのためクローズします。
