### ISSUE TITLE
lllyasviel SD Forge compatibility

### ISSUE THREAD

**Issue by diodiogod** [nihedon/sd-webui-weight-helper#6]
I can't live without you extension anymore. Any chance to make it work on Forge in the future? https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by nihedon** [comment]
@diodiogod 
Thank you so much for your kind words! I'm really glad to hear that you find the extension indispensable.

The extension already supports Forge. If you're experiencing issues with it not working on Forge, please first ensure that you have added the "LoRA Block Weight" to Forge. If it has been added and you're still facing issues, could you please check if there are any JavaScript errors by using your browser's debug tool?
https://github.com/nihedon/sd-webui-weight-helper/issues/1#issuecomment-1884714657

If you have any further questions or need assistance, please don't hesitate to reach out.

**Comment by diodiogod** [comment]
Hy, so I tried uninstalling both extensions. Open forge, close forge, installed again both using from "git clone" but the popup still does not show. Neither in Firefox or Edge. Also before I tested this I was using this [fork for SDNext ](https://github.com/RGX650/sd-webui-weight-helper-SDNEXT)that worked. But it is outdated compared to the how it is on my automatic1111 installation. 

The console (with the right extensions installed) shows this I don't know if I copied it correctly:

hello from injected code
contentscript.js:1 Hello from the content-script
weight_helper.js?1712370036.357269:964  Uncaught (in promise) ReferenceError: postAPI is not defined
    at weight_helper.js?1712370036.357269:964:9
    at HTMLDocument.<anonymous> (weight_helper.js?1712370036.357269:966:7)
127.0.0.1/:1 [Intervention]Images loaded lazily and replaced with placeholders. Load events are deferred. See https://go.microsoft.com/fwlink/?linkid=2048113

        [NEW] Explain Console errors by using Copilot in Edge: click 
         to explain an error. 
        Learn more
        Don't show again

**Comment by diodiogod** [comment]
This is from the console on firefox (i have no idea, but I think its the same thing):

Uncaught (in promise) ReferenceError: postAPI is not defined
    <anonymous> http://127.0.0.1:7860/file=extensions/sd-webui-weight-helper/javascript/weight_helper.js?1712370036.357269:964
    <anonymous> http://127.0.0.1:7860/file=extensions/sd-webui-weight-helper/javascript/weight_helper.js?1712370036.357269:966
[weight_helper.js:964:9](http://127.0.0.1:7860/file=extensions/sd-webui-weight-helper/javascript/weight_helper.js?1712370036.357269)
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data undefined

​

**Comment by diodiogod** [comment]
Working now! wow thank you so much, you are amazing!

**Comment by nihedon** [comment]
@diodiogod 
Thank you for your report!
Upon reviewing our implementation, we discovered that the issue was due to the use of a function defined in another extension, "TagAutocomplete."
I'm glad we were able to resolve this!

Please don't hesitate to contact us again if you encounter any more problems.
